replicaCount: 1

project: projectName
role: "segment-svc-role"

image:
  repository: 578089560574.dkr.ecr.eu-west-1.amazonaws.com/segment-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 50Mi
    cpu: 900m
  requests:
    memory: 20Mi
    cpu: 100m
