replicaCount: 2

project: projectName
role: "arn:aws:iam::408316150150:role/projectName-mongolog-role"

image:
  repository: 578089560574.dkr.ecr.eu-west-1.amazonaws.com/mongolog-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: "mongolog-service-projectName"
fullnameOverride: "mongolog-service-projectName"

resources:
  limits:
    memory: 60Mi
    cpu: 500m
  requests:
    memory: 40Mi
    cpu: 30m
