replicaCount: 1

project: projectName

image:
  repository: 578089560574.dkr.ecr.eu-west-1.amazonaws.com/project-frontend
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
  path: /
  hosts:
    - dev.example.com

  tls: true

resources:
  limits:
    memory: 50Mi
    cpu: 900m
  requests:
    memory: 5Mi
    cpu: 100m
