apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config-{{ .Release.Name }}
  labels:
    app: {{ include "cron.name" . }}
    chart: {{ include "cron.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $files := .Files }}
  appsettings.json: |-
{{ $files.Get "environment/appsettings.json"  | indent 4}}
