{{- if .Values.ingress.tls }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "backend-api.fullname" . }}
spec:
  secretName: {{ include "backend-api.fullname" . }}-crt-secret
  dnsNames:
{{- range .Values.ingress.hosts }}
  - {{ . | quote }}
{{- end }}
  acme:
    config:
    - http01:
        ingressClass: traefik
      domains:
      {{- range .Values.ingress.hosts }}
      - {{ . | quote }}
      {{- end }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}
