apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jenkins-crt
spec:
  secretName: jenkins-crt-secret
  dnsNames:
  - ci.example.com
  acme:
    config:
    - ingressClass: traefik
      domains:
      - ci.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
