role: "arn:aws:iam::408316150150:role/projectName-segmentcron-role"

image:
  repository: 578089560574.dkr.ecr.eu-west-1.amazonaws.com/segmentcron-service
  tag: development
  pullPolicy: IfNotPresent

schedule: "*/10 * * * *"
failedJobsHistoryLimit: 10
concurrencyPolicy: Forbid
restartPolicy: OnFailure

args:
  - /bin/sh
  - -c
  - date; dotnet ./SegmentCron.dll

resources:
  limits:
    memory: 700Mi
    cpu: 600m
  requests:
    memory: 50Mi
    cpu: 50m

persistentVolume:
  enabled: true
  annotations: {}
  accessModes:
    - ReadWriteMany
  size: 20Gi
  storageClass: "efs-retain"
