apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets-name" . }}-public
type: Opaque
stringData:
  publicKey: |-
    {{ .Values.secrets.publicKey }}
  signatureKey: |-
    {{ .Values.secrets.signatureKey }}
