replicaCount: 1

project: projectName
role: "arn:aws:iam::617172876354:role/projectName-role-write-role"

image:
  repository: 578089560574.dkr.ecr.eu-west-1.amazonaws.com/roles-write-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: "role-write-service-projectName"
fullnameOverride: "role-write-service-projectName"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 60Mi
    cpu: 500m
  requests:
    memory: 40Mi
    cpu: 25m

hpa:
  cpu: 75
  maxReplicas: 10
