replicaCount: 1

project: projectName
role: "arn:aws:iam::408316150150:role/projectName-card-role"

image:
  repository: 578089560574.dkr.ecr.eu-west-1.amazonaws.com/card-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: "card-service-projectName"
fullnameOverride: "card-service-projectName"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: traefik
     ingress.kubernetes.io/ssl-redirect: "true"
     traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
  path: /api/card
  hosts:
    - api.example.com
  tls: true

resources:
  limits:
    memory: 700Mi
    cpu: 600m
  requests:
    memory: 50Mi
    cpu: 50m

hpa:
  cpu: 75
  maxReplicas: 10
