apiVersion: v1
data:
  mapAccounts: |
    - "828821066173"
  mapUsers: |
    - userarn: arn:aws:iam::828821066173:user/pgeadas
      username: pgeadas
      groups:
        - system:masters
    - userarn: arn:aws:iam::786991263349:user/jenkins-helm
      username: jenkins-helm
      groups:
        - system:masters
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::786991263349:role/eksctl-production-nodegroup-ng-pr-NodeInstanceRole-1M1S7LJJ23TU4
      # TODO: rolearn: arn:aws:iam::786991263349:role/kubernetes-cluster-node-instance-role
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
