role: "hello-world-job-role"

image:
  repository: hello-world
  tag: latest
  pullPolicy: IfNotPresent
schedule: "* * * * *"
failedJobsHistoryLimit: 1
successfulJobsHistoryLimit: 3
concurrencyPolicy: Allow
restartPolicy: OnFailure