role: "hello-env-var-job-role"

image:
  repository: busybox
  tag: latest
  pullPolicy: Always
# optional env vars
env:
- name: ECHO_VAR
  value: "busybox"
schedule: "* * * * *"
command: ["/bin/sh"]
args:
  - "-c"
  - "echo $(date) - hello from $ECHO_VAR"
resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 256Mi
failedJobsHistoryLimit: 1
successfulJobsHistoryLimit: 3
concurrencyPolicy: Forbid
restartPolicy: Never
nodeSelector:
  type: infra
tolerations:
- effect: NoSchedule
  operator: Exists
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/e2e-az-name
          operator: In
          values:
          - e2e-az1
          - e2e-az2
