{{- if .Values.sftpConfig.authorizedKeys }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sftp-server.fullname" . }}-authorized-keys
data:
  id_rsa.pub: |
    {{- range .Values.sftpConfig.authorizedKeys }}
    {{ . }}
    {{- end }}
{{- end }}
